<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="10" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="40813" started-at="2016-11-10T20:41:04Z" finished-at="2016-11-10T20:41:45Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="40813" started-at="2016-11-10T20:41:04Z" finished-at="2016-11-10T20:41:45Z">
      <class name="com.test.HomePageTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.test.HomePageTest@61832929]" name="beforeSuite" is-config="true" duration-ms="14222" started-at="2016-11-10T12:40:50Z" finished-at="2016-11-10T12:41:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:com.test.HomePageTest@61832929]" name="initialize" is-config="true" duration-ms="60" started-at="2016-11-10T12:41:04Z" finished-at="2016-11-10T12:41:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="testCountSocialIcons()[pri:0, instance:com.test.HomePageTest@61832929]" name="testCountSocialIcons" duration-ms="99" started-at="2016-11-10T12:41:04Z" finished-at="2016-11-10T12:41:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCountSocialIcons -->
        <test-method status="PASS" signature="testLoginLink()[pri:0, instance:com.test.HomePageTest@61832929]" name="testLoginLink" duration-ms="1545" started-at="2016-11-10T12:41:04Z" finished-at="2016-11-10T12:41:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoginLink -->
        <test-method status="PASS" signature="testactions()[pri:0, instance:com.test.HomePageTest@61832929]" name="testactions" duration-ms="10110" started-at="2016-11-10T12:41:06Z" finished-at="2016-11-10T12:41:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testactions -->
        <test-method status="FAIL" signature="testisLogoPresent()[pri:0, instance:com.test.HomePageTest@61832929]" name="testisLogoPresent" duration-ms="1" started-at="2016-11-10T12:41:16Z" finished-at="2016-11-10T12:41:16Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.page.HomePage.isLogoPresent(HomePage.java:64)
	at com.test.HomePageTest.testisLogoPresent(HomePageTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testisLogoPresent -->
        <test-method status="FAIL" signature="testnavbar()[pri:0, instance:com.test.HomePageTest@61832929]" name="testnavbar" duration-ms="2" started-at="2016-11-10T12:41:16Z" finished-at="2016-11-10T12:41:16Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Cannot find elements when the selector is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Cannot find elements when the selector is null
	at org.openqa.selenium.By.cssSelector(By.java:145)
	at com.util.Locators.get(Locators.java:91)
	at com.util.PageDriver.findElements(PageDriver.java:81)
	at com.page.HomePage.navbar(HomePage.java:56)
	at com.test.HomePageTest.testnavbar(HomePageTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testnavbar -->
        <test-method status="PASS" signature="testoptions()[pri:0, instance:com.test.HomePageTest@61832929]" name="testoptions" duration-ms="12557" started-at="2016-11-10T12:41:16Z" finished-at="2016-11-10T12:41:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testoptions -->
        <test-method status="PASS" signature="testscreenShot()[pri:0, instance:com.test.HomePageTest@61832929]" name="testscreenShot" duration-ms="14009" started-at="2016-11-10T12:41:28Z" finished-at="2016-11-10T12:41:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testscreenShot -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.test.HomePageTest@61832929]" name="afterSuite" is-config="true" duration-ms="1479" started-at="2016-11-10T12:41:45Z" finished-at="2016-11-10T12:41:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.test.HomePageTest -->
      <class name="com.test.LoginPageTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.test.LoginPageTest@5e3a8624]" name="beforeClass" is-config="true" duration-ms="45" started-at="2016-11-10T12:41:42Z" finished-at="2016-11-10T12:41:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="performLogin(java.lang.String, java.lang.String)[pri:0, instance:com.test.LoginPageTest@5e3a8624]" name="performLogin" duration-ms="1" started-at="2016-11-10T12:41:45Z" data-provider="userData" finished-at="2016-11-10T12:41:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.page.LoginPage.performLogin(LoginPage.java:35)
	at com.test.LoginPageTest.performLogin(LoginPageTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- performLogin -->
        <test-method status="FAIL" signature="performLogin(java.lang.String, java.lang.String)[pri:0, instance:com.test.LoginPageTest@5e3a8624]" name="performLogin" duration-ms="1" started-at="2016-11-10T12:41:45Z" data-provider="userData" finished-at="2016-11-10T12:41:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test1@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.page.LoginPage.performLogin(LoginPage.java:35)
	at com.test.LoginPageTest.performLogin(LoginPageTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- performLogin -->
        <test-method status="FAIL" signature="performLogin(java.lang.String, java.lang.String)[pri:0, instance:com.test.LoginPageTest@5e3a8624]" name="performLogin" duration-ms="1" started-at="2016-11-10T12:41:45Z" data-provider="userData" finished-at="2016-11-10T12:41:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test2@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.page.LoginPage.performLogin(LoginPage.java:35)
	at com.test.LoginPageTest.performLogin(LoginPageTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- performLogin -->
      </class> <!-- com.test.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
